#!/usr/bin/env node
//=============================================================================
//
// File:         gcsio
// Language:     JavaScript
// Author:       Joe Honton © 2022
// License:      JavaScript Orthographic Earth Software License Agreement
// Contents:     CLI entry point 
//
//=============================================================================

import CLI from './api/cli.js';
var cli = new CLI();

// Read the command line and execute
if (cli.validateOptions())
	cli.execute();
